CREATE DATABASE SAMPLE;
DROP DATABASE SAMPLE;
CREATE DATABASE EMPLOYEE;
SHOW DATABASES;
USE MYSQL;
USE EMPLOYEE;

SHOW TABLES;
DESCRIBE DETAILS;

create table details(
	ID TINYINT NOT NULL AUTO_INCREMENT,
    NAME MEDIUMTEXT NOT NULL,
    AGE TINYINT NOT NULL,
    PRIMARY KEY(ID)
);
DESCRIBE DETAILS;

CREATE TABLE SALARY( 
    ID TINYINT NOT NULL AUTO_INCREMENT ,
    AMOUNT INT NOT NULL,
    PRIMARY KEY(ID)
);

INSERT INTO DETAILS VALUES(NULL, 'GEORGE', 18, 'AFRICA'),(NULL, 'DIANA', 20, 'NEW ZELAND');
SELECT * FROM DETAILS;

UPDATE DETAILS SET ID = 4 WHERE ID=5;
UPDATE DETAILS SET ID = 5 WHERE ID =6;  

DELETE FROM DETAILS WHERE ID = 5;

INSERT INTO DETAILS VALUES(NULL, 'HENRY', 24, 'AMERICA');

UPDATE DETAILS SET ID = 5 WHERE ID =7;

SELECT ID,NAME,AGE FROM DETAILS;
SELECT ID,NAME FROM DETAILS WHERE AGE > 20;
SELECT NAME FROM DETAILS WHERE AGE <= 21 AND PLACE = 'AMERICA';
SELECT COUNT(NAME) AS TOTAL FROM DETAILS;


INSERT INTO DETAILS VALUES(NULL,'TOM',21,'EUROPE'),(NULL,'ROBERT',23,'AFRICA'),(NULL,'LEONARDS',25,'AMERICA'),
(NULL,'CRUISE',27,'FRANCE'),(NULL,'BRAD PITT',29,'AFRICA'),(NULL,'JOHNNY',20,'FRANCE'),(NULL,'DENZEL',24,'AMERICA'),(NULL,'JACKSON',22,'ENGLAND'),
(NULL,'SMITH',26,'JAPAN'),(NULL,'ROBERT',28,'ENGLAND'),(NULL,'ANTHONY',21,'AFRICA'),(NULL,'MORGAN',23,'ENGLAND'),(NULL,'CHRIS',25,'RUSSIA'),
(NULL,'VIN DIESEL',27,'ENGLAND'),(NULL,'PACINO',29,'AMERICA'),(NULL,'JACKMAN',22,'FRANCE'),(NULL,'CHRIS',24,'AFRICA'),(NULL,'NELSON',26,'NEW ZELAND'),
(NULL,'STALLON',28,'AMERICA'),(NULL,'JOHNSON',21,'CHINA'),(NULL,'COOPER',23,'FRANCE'),(NULL,'DANIEL',25,'GERMANY'),(NULL,'MATT DAMON',27,'AFRICA');

SELECT * FROM DETAILS;

SELECT COUNT(ID) AS TOTAL_EMPLOYEE FROM DETAILS;

INSERT INTO DETAILS VALUES(6,'SMITH',23,'RUSSIA'), (7,'ALEX', 19, 'CANADA');

SELECT NAME FROM DETAILS WHERE AGE <25 AND PLACE = 'AMERICA';

SELECT NAME FROM DETAILS WHERE AGE < 24 AND (PLACE = 'FRANCE' OR PLACE = 'AFRICA') ORDER BY NAME;

SELECT NAME,AGE FROM DETAILS ORDER BY AGE;

SELECT COUNT(NAME) AS TOTAL_STUDENTS FROM DETAILS;

SELECT * FROM DETAILS ORDER BY ID;

SELECT DISTINCT PLACE FROM DETAILS ORDER BY PLACE;

SELECT DISTINCT AGE FROM DETAILS ORDER BY AGE;

SELECT MIN(AGE) FROM DETAILS;
SELECT MAX(AGE) FROM DETAILS;
SELECT ROUND(AVG(AGE)) FROM DETAILS;
SELECT SUM(AGE) FROM DETAILS;

SELECT DISTINCT AGE FROM DETAILS ORDER BY AGE DESC;

SELECT AGE,COUNT(AGE) FROM DETAILS GROUP BY AGE;
SELECT PLACE,COUNT(PLACE) FROM DETAILS GROUP BY PLACE;

SELECT * FROM DETAILS ORDER BY ID DESC LIMIT 0,1;
SELECT * FROM DETAILS ORDER BY ID LIMIT 0,10;
SELECT * FROM DETAILS ORDER BY ID LIMIT 10,10;
SELECT * FROM DETAILS ORDER BY ID LIMIT 20,10;

SELECT DISTINCT NAME FROM DETAILS WHERE NAME LIKE 'S%' ;
SELECT NAME FROM DETAILS WHERE NAME LIKE '%ON';
SELECT * FROM DETAILS WHERE NAME LIKE 'H%Y';
SELECT * FROM DETAILS WHERE NAME LIKE 'SARA';

SELECT * FROM DETAILS WHERE PLACE IN('FRANCE', 'JAPAN');
SELECT * FROM DETAILS WHERE PLACE NOT IN('EUROPE', 'AFRICA');

SELECT COUNT(ID) AS TOTAL_EMPLOYEE FROM DETAILS WHERE PLACE NOT IN('EUROPE', 'AFRICA');

SELECT NAME,AGE FROM DETAILS WHERE AGE BETWEEN 20 AND 25;
SELECT NAME,AGE FROM DETAILS WHERE AGE NOT BETWEEN 21 AND 24;

SELECT * FROM SALARY;
SELECT * FROM DETAILS;

INSERT INTO SALARY VALUES(NULL,10000),(NULL,20000),(NULL,15000),(NULL,17000),(NULL,18000),(NULL,8000),
(NULL,11000),(NULL,13000),(NULL,10800),(NULL,11900),(NULL,14000),(NULL,16000),(NULL,12500),(NULL,14500),
(NULL,11000),(NULL,10500),(NULL,12500),(NULL,16500),(NULL,17000),(NULL,15000);

INSERT INTO SALARY VALUES(NULL,14000),(NULL,20000),(NULL,15600),(NULL,17000),(NULL,18500),(NULL,8000),
(NULL,11000),(NULL,13000),(NULL,10800),(NULL,11600);

SELECT DETAILS.NAME,DETAILS.AGE,SALARY.AMOUNT 
FROM DETAILS INNER JOIN SALARY
ON DETAILS.ID = SALARY.ID;

SELECT DETAILS.NAME,DETAILS.AGE,SALARY.AMOUNT,
(
	CASE
    WHEN DETAILS.AGE=18 THEN 2000
    WHEN DETAILS.AGE=19 THEN 1750
    WHEN DETAILS.AGE=20 THEN 1500
    WHEN DETAILS.AGE=21 THEN 1000
    WHEN DETAILS.AGE=22 THEN 900 
    WHEN DETAILS.AGE=23 THEN 800
    WHEN DETAILS.AGE=24 THEN 700
    WHEN DETAILS.AGE=25 THEN 600 
    WHEN DETAILS.AGE=26 THEN 500
    WHEN DETAILS.AGE=27 THEN 400
    WHEN DETAILS.AGE=28 THEN 300 
    WHEN DETAILS.AGE=29 THEN 200
    ELSE 100
    
    END
)  AS BONOUS
FROM DETAILS INNER JOIN SALARY
ON DETAILS.ID = SALARY.ID;

SELECT DISTINCT AGE FROM DETAILS ORDER BY AGE;

/* THANKS AM I WRITE THIS MYSQL CODE FOR MY OWN 
   I WILL REFER FROM TUTOR JOES YOUTUBE CHANNEL */ 